package dev.konraditurbe.osmosis.rsdk

import org.junit.Assert.*
import org.junit.Test

/**
 * Locks the R-SDK encoder to DJI's own output. The three expected frames were generated by compiling
 * the Osmo-GPS-Controller-Demo's CRC + framing code (`custom_crc16.c`, `custom_crc32.c`) with fixed
 * inputs (scratchpad `rsdk_golden.c`) — so a byte-for-byte match proves our framing, both CRCs, the
 * little-endian field packing and the float encoding are all correct.
 */
class RsdkProtocolTest {

    private fun hex(b: ByteArray) = b.joinToString("") { "%02X".format(it) }

    @Test fun connectionRequestMatchesGolden() {
        val mac = byteArrayOf(0x38, 0x34, 0x56, 0x78, 0x9A.toByte(), 0xBC.toByte())
        val payload = RsdkProtocol.connectionRequest(deviceId = 0x12345678, mac = mac, verifyMode = 0, verifyData = 1234)
        val frame = RsdkProtocol.frame(0x00, 0x19, RsdkProtocol.CMD_WAIT_RESULT, payload, seq = 1)
        assertEquals(
            "AA330002000000000100982F00197856341206383456789ABC00000000000000000000000000000000D20400000000A70F381B",
            hex(frame),
        )
    }

    @Test fun gpsPushMatchesGolden() {
        val payload = RsdkProtocol.gpsPush(
            yearMonthDay = 20260718, hourMinuteSecond = 143005,
            longitude1e7 = 21600000, latitude1e7 = 414000000, heightMm = 42000,
            speedNorthCmS = 12.5f, speedEastCmS = -3.25f, speedDownCmS = 0.0f,
            vertAccMm = 1000, horizAccMm = 1000, speedAccCmS = 10, satellites = 11,
        )
        val frame = RsdkProtocol.frame(0x00, 0x17, RsdkProtocol.CMD_NO_RESPONSE, payload, seq = 2)
        assertEquals(
            "AA420000000000000200D34D00176E2735019D2E0200009749018023AD1810A4000000004841000050C000000000E8030000E80300000A0000000B000000FE2937C4",
            hex(frame),
        )
    }

    @Test fun statusSubscriptionMatchesGolden() {
        val payload = RsdkProtocol.statusSubscription(pushMode = 2, pushFreq = 20)
        val frame = RsdkProtocol.frame(0x1D, 0x05, RsdkProtocol.CMD_NO_RESPONSE, payload, seq = 3)
        assertEquals("AA180000000000000300507E1D05021400000000FA4A4931", hex(frame))
    }

    @Test fun parseRoundTripsAndValidatesCrc() {
        val payload = RsdkProtocol.statusSubscription(2, 20)
        val frame = RsdkProtocol.frame(0x1D, 0x05, RsdkProtocol.CMD_NO_RESPONSE, payload, seq = 3)
        val parsed = RsdkProtocol.parse(frame)!!
        assertEquals(0x1D, parsed.cmdSet)
        assertEquals(0x05, parsed.cmdId)
        assertEquals(3, parsed.seq)
        assertFalse(parsed.isResponse)
        assertArrayEquals(payload, parsed.payload)
        // A single flipped byte must fail the CRC check.
        frame[20] = (frame[20] + 1).toByte()
        assertNull(RsdkProtocol.parse(frame))
    }

    @Test fun parsesCameraStatusModeAndRecording() {
        // camera_mode=0x01 (Video), camera_status=0x03 (recording), res=103, fps=3, record_time=5, battery=77 at end.
        val p = ByteArray(46)
        p[0] = 0x01; p[1] = 0x03; p[2] = 103; p[3] = 3; p[5] = 5; p[45] = 77
        val s = RsdkProtocol.parseCameraStatus(p)!!
        assertEquals("Video", s.modeName)
        assertTrue(s.recording)
        assertEquals(77, s.battery)
    }
}
